### ISSUE TITLE
Potential nullreference in LoggingHandler

### ISSUE THREAD

**Issue by kaweera** [UlrichFreiberg/STF#66]
at Microsoft.Practices.Unity.InterceptionExtension.ParameterCollection.<>c__DisplayClass7.<IndexOf>b__6(ArgumentInfo info)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at Microsoft.Practices.Unity.InterceptionExtension.ParameterCollection.IndexOf(Object value)
   at Mir.Stf.Utilities.Interceptors.LoggingHandler.CreateStringFromParameterCollection(IParameterCollection parameterCollection)
   at Mir.Stf.Utilities.Interceptors.LoggingHandler.LogThisMessage(MethodBase methodBase, LogMessageType messageType, IParameterCollection inputs, String returnTypeName, Object returnValue)
   at Mir.Stf.Utilities.Interceptors.LoggingHandler.Invoke(IMethodInvocation input, GetNextHandlerDelegate getNext)
   at Microsoft.Practices.Unity.InterceptionExtension.HandlerPipeline.Invoke(IMethodInvocation input, InvokeHandlerDelegate target)
   at Microsoft.Practices.Unity.InterceptionExtension.PolicyInjectionBehavior.Invoke(IMethodInvocation input, GetNextInterceptionBehaviorDelegate getNext)
   at Microsoft.Practices.Unity.InterceptionExtension.InterceptionBehaviorPipeline.Invoke(IMethodInvocation input, InvokeInterceptionBehaviorDelegate target)
   at DynamicModule.ns.Wrapped_ISearch_a5e25d50440c4b9e829927520cd83ced.set_CaReference(String value)
   at Nordea.Stf.DisplayTargets.ImSecurities.Shell.ImShell.GetGoldenRecord(String caRef) in c:\Projects\TestTools\TestFramework\Source\DisplayTargets\ImSecurities\ImSecuritiesShell\ImShell.cs:line 421
   at DynamicModule.ns.Wrapped_IImShell_425fb2ed3c6644f395c23c29604a6a0f.<GetGoldenRecord_DelegateImplementation>__13(IMethodInvocation inputs, GetNextInterceptionBehaviorDelegate getNext)

**Comment by kaweera** [comment]
Fixed in an earlier commit... :)
